In [0]:
# Load the Drive helper and mount
from google.colab import drive

# This will prompt for authorization.
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
import os
from skimage.io import imread
import numpy as np
from PIL import Image
from matplotlib import pyplot as plt

# Image dimensions checker
top_path = '/content/drive/My Drive/pokemon/dataset/'
images_size = []
for classification_path in os.listdir(top_path):
    for image_path in os.listdir(str(top_path)+str(classification_path)):
        img = Image.open(str(top_path)+str(classification_path)+ '//' + str(image_path))
        print(img.size)
        

"import os\nfrom skimage.io import imread\nimport numpy as np\nfrom PIL import Image\nfrom matplotlib import pyplot as plt\n\n# Image dimensions checker\ntop_path = '/content/drive/My Drive/pokemon/dataset/'\nimages_size = []\nfor classification_path in os.listdir(top_path):\n    for image_path in os.listdir(str(top_path)+str(classification_path)):\n        img = Image.open(str(top_path)+str(classification_path)+ '//' + str(image_path))\n        print(img.size)\n        "

In [0]:
import os
from skimage.io import imread
import numpy as np
from PIL import Image
from matplotlib import pyplot as plt

# Image loader
top_path = '/content/drive/My Drive/Colab Notebooks/Retina_dl/'
all_images = []
all_classification = []
for classification_path in os.listdir(top_path):
    for image_path in os.listdir(str(top_path)+str(classification_path)):
        img = Image.open(str(top_path)+str(classification_path)+ '//' + str(image_path))
        arr = np.array(img)
        resized_img = np.array(Image.fromarray(arr).resize((256,256)))
        all_images.append(resized_img)
        all_classification.append(classification_path)
x = np.array(all_images)
y = np.array(all_classification)

In [0]:
x=x/255
print(x.shape)

(631, 256, 256, 3)


In [0]:
print(y.shape)

(631,)


In [0]:
#Declarations
from keras.models import Sequential
from keras.layers import Dense, Conv2D, Flatten, Conv2D, MaxPooling2D, Dropout
from sklearn.preprocessing import LabelBinarizer, LabelEncoder
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
from keras.callbacks import ModelCheckpoint
from sklearn.metrics import confusion_matrix
from keras.utils import np_utils

In [0]:
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)
y = np_utils.to_categorical(y)

In [0]:
#create model
model = Sequential()
#add model layers
model.add(Conv2D(64, kernel_size=3, activation='relu', input_shape=(256,256,3)))
model.add(Conv2D(32, kernel_size=3, activation='relu'))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(3, activation='softmax'))

In [0]:
model.compile(loss="categorical_crossentropy",metrics=['accuracy'],optimizer='adam')

In [0]:
filepath = "weigths.best.hdf5"

In [0]:
checkpoint = ModelCheckpoint(filepath,monitor='val_acc',verbose=1,save_best_only = True, mode = 'max')

In [0]:
callbacks_list = [checkpoint]

In [0]:
x_train,x_valid,y_train, y_valid = train_test_split(x,y,test_size=0.2)

In [0]:
model.fit(x_train,y_train,validation_data=[x_valid,y_valid], nb_epoch = 200, batch_size=64,callbacks=callbacks_list)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Train on 504 samples, validate on 127 samples
Epoch 1/200
504/504 [==============================] - 9s 17ms/step - loss: 1.7630 - acc: 0.5417 - val_loss: 0.8836 - val_acc: 0.4961

Epoch 00001: val_acc improved from -inf to 0.49606, saving model to weigths.best.hdf5
Epoch 2/200
504/504 [==============================] - 8s 16ms/step - loss: 0.5903 - acc: 0.7123 - val_loss: 0.5698 - val_acc: 0.7638

Epoch 00002: val_acc improved from 0.49606 to 0.76378, saving model to weigths.best.hdf5
Epoch 3/200
504/504 [==============================] - 8s 16ms/step - loss: 0.3887 - acc: 0.8452 - val_loss: 0.3817 - val_acc: 0.8346

Epoch 00003: val_acc improved from 0.76378 to 0.83465, saving model to weigths.best.hdf5
Epoch 4/200
504/504 [==============================] - 8s 16ms/step - loss: 0.3346 - acc: 0.8571 - val_loss: 0.3552 - val_acc: 0.8661

Epoch 00004: val_acc improved from 0.83465 to 0.86614, saving model to weigths.best.hdf5
Epoch 5/200
504/504 [==============================] - 8s 16m

In [0]:
# Image loader
top_path = '/content/drive/My Drive/Colab Notebooks/validation/'
all_images = []
all_classification = []
for classification_path in os.listdir(top_path):
    for image_path in os.listdir(str(top_path)+str(classification_path)):
        img = Image.open(str(top_path)+str(classification_path)+ '//' + str(image_path))
        arr = np.array(img)
        resized_img = np.array(Image.fromarray(arr).resize((256,256)))
        all_images.append(resized_img)
        all_classification.append(classification_path)
x_test = np.array(all_images)
y_test = np.array(all_classification)

In [0]:
x_test = x_test/255

In [0]:
y_test = label_encoder.transform(y_test)
y_test_one=np_utils.to_categorical(y_test)

In [0]:
y_predict = model.predict_classes(x_test)
y_predict

array([2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 1,
       1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [0]:
scores = model.evaluate(x_test,y_test_one,verbose=0)
print(model.metrics_names[1], scores[1]*100)

acc 92.85714370863778


In [0]:
y_test

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [0]:
confusion_matrix(y_test,y_predict)

array([[11,  0,  0],
       [ 0, 13,  2],
       [ 0,  2, 28]])